### ISSUE TITLE
Confusion about Heterogeneity Block

### ISSUE THREAD

**Issue by spidercatfly** [YujieMo/HomHet#1]
Hi, thanks for your excellent work!

I am a little confused about the heterogeneity block in the model. If two nodes (1-hop neighborhood with each other) are verified by the homophily block that they are not similar, why should they also need the message passing in the heterogeneity block?

Another question is, why does the heterogeneity block only consider 1-hop neighbors, rather than more hops?

Thanks for your help.

**Comment by YujieMo** [comment]
Thanks for your interest on our work!
First, the heterogeneity block is used to aggregate information of nodes (e.g., paper_1, author_1) from different types while homophily block is used to aggregate information of nodes (e.g., author_1 and author_2) within the same class. Therefore, the heterogeneity and homophily blocks are totally different in information aggregation.
Second, we can consider multi-hop neighbors in the heterogeneity module by stacking layers. Actually, we use 1 layer for the ACM dataset and 2 layer for other datasets.

**Comment by spidercatfly** [comment]
Got it! Thanks for your explanation.

Does this mean that the homophily module focuses on message passing among nodes that belong to the same class, and the heterogeneity module focuses on message passing between class-inter nodes that are connected by 1-hop or multi-hop edges?

And do the nodes in the same class not necessarily belong to the same type, depending on the threshold selection?

**Comment by YujieMo** [comment]
Your understanding is partially correct. The homophily module focuses on message passing among nodes that may belong to the same class, and the heterogeneity module focuses on message passing between different types of nodes. Moreover, the nodes in the same class must belong to the same type.

**Comment by spidercatfly** [comment]
Thanks for your help. It's clear now.
Nice work! There is no need to manually select meta-paths!

**Comment by YujieMo** [comment]
You're welcome! I'm glad it's clear now. If you have any more questions or need further assistance, feel free to reach out us!
